/** Common vehicle makes and models on Kenyan roads for cascading form dropdowns. */
export const CAR_MODELS_BY_MAKE = {
  Toyota: [
    'Axio',
    'Allion',
    'Aqua',
    'Auris',
    'Avalon',
    'Avensis',
    'C-HR',
    'Camry',
    'Corolla',
    'Corolla Fielder',
    'Corolla Cross',
    'Crown',
    'Fortuner',
    'Harrier',
    'Hiace',
    'Hilux',
    'Land Cruiser',
    'Land Cruiser Prado',
    'Mark X',
    'Noah',
    'Passo',
    'Premio',
    'Probox',
    'RAV4',
    'Rush',
    'Succeed',
    'Vitz',
    'Voxy',
    'Wish',
  ],
  Nissan: [
    'AD Van',
    'Dualis',
    'Juke',
    'March',
    'Murano',
    'Navara',
    'Note',
    'NP200',
    'NP300',
    'NV200',
    'Pathfinder',
    'Patrol',
    'Qashqai',
    'Serena',
    'Sunny',
    'Sylphy',
    'Tiida',
    'X-Trail',
  ],
  Mazda: [
    'Atenza',
    'Axela',
    'BT-50',
    'CX-3',
    'CX-5',
    'CX-7',
    'CX-8',
    'CX-9',
    'Demio',
    'Premacy',
    'Verisa',
  ],
  Subaru: [
    'Forester',
    'Impreza',
    'Legacy',
    'Levorg',
    'Outback',
    'XV',
  ],
  Honda: [
    'Accord',
    'Civic',
    'CR-V',
    'Fit',
    'Freed',
    'HR-V',
    'Insight',
    'Stream',
    'Vezel',
  ],
  Mitsubishi: [
    'ASX',
    'Canter',
    'Colt',
    'Galant',
    'Lancer',
    'Outlander',
    'Pajero',
    'Pajero Sport',
    'RVR',
  ],
  Isuzu: [
    'D-Max',
    'FRR',
    'FSR',
    'FTR',
    'MU-X',
    'NQR',
    'Trooper',
  ],
  Suzuki: [
    'Alto',
    'Baleno',
    'Carry',
    'Celerio',
    'Dzire',
    'Ertiga',
    'Grand Vitara',
    'Jimny',
    'Swift',
    'Vitara',
    'Wagon R',
  ],
  'Mercedes-Benz': [
    'A-Class',
    'B-Class',
    'C-Class',
    'E-Class',
    'G-Class',
    'GLA',
    'GLC',
    'GLE',
    'ML',
    'S-Class',
    'Sprinter',
    'Vito',
  ],
  BMW: [
    '1 Series',
    '2 Series',
    '3 Series',
    '5 Series',
    '7 Series',
    'X1',
    'X3',
    'X5',
    'X6',
  ],
  Volkswagen: [
    'Amarok',
    'Caddy',
    'Golf',
    'Jetta',
    'Passat',
    'Polo',
    'Tiguan',
    'Touareg',
    'Transporter',
  ],
  Ford: [
    'EcoSport',
    'Everest',
    'Fiesta',
    'Focus',
    'Ranger',
    'Transit',
  ],
  Peugeot: [
    '206',
    '207',
    '208',
    '3008',
    '307',
    '308',
    '407',
    '508',
    'Partner',
  ],
  'Land Rover': [
    'Defender',
    'Discovery',
    'Discovery Sport',
    'Freelander',
    'Range Rover',
    'Range Rover Evoque',
    'Range Rover Sport',
  ],
  Hyundai: [
    'Accent',
    'Creta',
    'Elantra',
    'i10',
    'i20',
    'Santa Fe',
    'Tucson',
  ],
  Kia: [
    'Cerato',
    'Picanto',
    'Rio',
    'Seltos',
    'Sorento',
    'Sportage',
  ],
  Audi: [
    'A3',
    'A4',
    'A6',
    'Q3',
    'Q5',
    'Q7',
  ],
  Volvo: [
    'S60',
    'S90',
    'V40',
    'XC60',
    'XC90',
  ],
  Jeep: [
    'Cherokee',
    'Compass',
    'Grand Cherokee',
    'Wrangler',
  ],
  Chevrolet: [
    'Aveo',
    'Captiva',
    'Cruze',
    'Spark',
    'Trailblazer',
  ],
  Daihatsu: [
    'Boon',
    'Charade',
    'Mira',
    'Terios',
  ],
  Hino: [
    '300 Series',
    '500 Series',
    '700 Series',
  ],
  Fuso: [
    'Canter',
    'Fighter',
    'Rosa',
  ],
  Scania: [
    'P-Series',
    'R-Series',
    'G-Series',
  ],
  MAN: [
    'TGM',
    'TGS',
    'TGX',
  ],
}

export const CAR_MAKES = Object.keys(CAR_MODELS_BY_MAKE)

export const CAR_MAKE_OPTIONS = [
  { value: '', label: 'Select make' },
  ...CAR_MAKES.map(name => ({ value: name, label: name })),
  { value: 'Other', label: 'Other' },
]

/** Model options for a selected make. Empty make → prompt only. */
export function getCarModelOptions(make) {
  if (!make || make === 'Other') {
    return [{ value: '', label: 'Select make first' }]
  }

  const models = CAR_MODELS_BY_MAKE[make] ?? []
  return [
    { value: '', label: 'Select model' },
    ...models.map(name => ({ value: name, label: name })),
    { value: 'Other', label: 'Other' },
  ]
}
